import CodeGeneration
import Foundation

public class ScalaAstGenerator {

	private let defaultScalaOutFileUrl = URL(fileURLWithPath: "./SwiftNodeSyntax.scala")

	private func baseNode(node: Node) -> String {
		String(describing: node.base.syntaxType)
	}

	private func inheritsFrom(node: Node) -> [String] {
		let base = baseNode(node: node)
		let traits = node.layoutNode?.traits ?? []
		return [base] + traits
	}

	private func dateString() -> String {
		let currentDateTime = Date()
		let formatter = DateFormatter()
		formatter.timeStyle = .long
		formatter.dateStyle = .long
		return formatter.string(from: currentDateTime)
	}

	private func backtickedIfNeeded(name: String) -> String {
		if name == "type" { return "`\(name)`" } else { return name }
	}

	private func header() -> String {
		return """
		// Automatically generated by 'SwiftAstGen --scalaAstOnly'.
		// Do not edit directly!
		// Generated: \(dateString())

		import ujson.Value
		"""
	}

	public init() throws {
		if FileManager.default.fileExists(atPath: defaultScalaOutFileUrl.path) {
			try FileManager.default.removeItem(at: defaultScalaOutFileUrl)
		}
		_ = FileManager.default.createFile(
			atPath: defaultScalaOutFileUrl.path,
			contents: nil,
			attributes: nil
		)
	}

	public func generate() throws {
		let allBaseNodeNames = Set(SYNTAX_NODES.map(baseNode)).map { "\($0)" }

		let baseNodes = allBaseNodeNames.map {
			"""
			sealed trait \($0) extends SwiftNode
			"""
		}

		let allTraits = TRAITS.map {
			if $0.documentation.isEmpty {
				"sealed trait \($0.traitName)"
			} else {
				"""
				\n\t\(String(describing: $0.documentation).replacingOccurrences(of: "\n", with: "\n\t"))
				\tsealed trait \($0.traitName)
				"""
			}
		}

		let allNodes = NON_BASE_SYNTAX_NODES.map { node in
			let syntaxType = node.kind.syntaxType
			let inherits = inheritsFrom(node: node)
			let inheritsString =
				if inherits.count == 1 {
					"extends \(inherits[0])"
				} else {
					"extends \(inherits[0]) with \(inherits[1...inherits.count-1].joined(separator: " with "))"
				}

			let allChildren = node.layoutNode?.children ?? []
			var childrenString = ""
			if allChildren.count != 0 {
				childrenString =
					allChildren
					.filter { !$0.isUnexpectedNodes }
					.map { child in
						let name = backtickedIfNeeded(name: "\(child.varOrCaseName)")
						let childType = TypeGenerator.type(for: child)
						if child.isOptional {
							return "\tdef \(name): Option[\(childType)] = _childrenMap.get(\"\(child.varOrCaseName)\").map(c => createSwiftNode(c).asInstanceOf[\(childType)])"
						} else {
							return "\tdef \(name): \(childType) = createSwiftNode(_childrenMap(\"\(child.varOrCaseName)\")).asInstanceOf[\(childType)]"
						}
					}.joined(separator: "\n\t")
			} else {
				let collection = node.collectionNode!
				let elementType = TypeGenerator.collectionElementType(for: collection)
				childrenString =
					"\tdef children: Seq[\(elementType)] = json(\"children\").arr.iterator.map(c => createSwiftNode(c).asInstanceOf[\(elementType)]).toSeq"
			}

			var documentation = String(describing: node.documentation)
			if documentation.isEmpty {
				documentation = "/// No documentation available."
			} else {
				documentation = documentation.replacingOccurrences(of: "\n", with: "\n\t")
			}

			let childrenDoc =
				node.layoutNode?.grammar ?? node.collectionNode?.grammar ?? "/// no children available"
			let childrenDocString = String(describing: childrenDoc).replacingOccurrences(
				of: "\n", with: "\n\t")

			var containedInDocString = String(describing: node.containedIn)
			containedInDocString = containedInDocString.replacingOccurrences(of: "\n", with: "\n\t")

			let docString = """
				\n\t/**
				\t/// ### Documentation
				\t///
				\t\(documentation)
				\t///
				\t\(childrenDocString)
				\t///
				\t\(containedInDocString.isEmpty ? "/// ### Nowhere contained in" : containedInDocString)
				\t */
				"""
				.replacingOccurrences(of: "///", with: " *")
				.replacingOccurrences(of: "```swift", with: "{{{")
				.replacingOccurrences(of: "```", with: "}}}")

			return """
				\(docString)
				\tcase class \(syntaxType)(json: Value) \(inheritsString) {
					\(childrenString)
				\t}
				"""
		}

		let allToken = Token.allCases.map {
			"""
			case class \($0)(json: Value) extends SwiftToken
			"""
		}

		let nodeTypeMapEntries = NON_BASE_SYNTAX_NODES.map { node in
			let syntaxType = node.kind.syntaxType
			return "\"\(syntaxType)\" -> (json => \(syntaxType)(json))"
		}
		let nodeTypeMapEntriesString = (nodeTypeMapEntries + ["\"TokenSyntax\" -> (json => TokenSyntax(json))"]).joined(separator: ",\n\t\t\t")

		let tokenKindMapEntries = Token.allCases.map { "\"\($0)\" -> (json => \($0)(json))" }
		let tokenKindMapEntriesString = tokenKindMapEntries.joined(separator: ",\n\t\t\t")

		let out = """
			\(header())

			object SwiftNodeSyntax {

				def createSwiftNode(json: Value): SwiftNode = {
					val nodeType = json("nodeType").str
					val tokenKind = json("tokenKind").str

					if (nodeType.nonEmpty) {
						_nodeTypeMap.getOrElse(nodeType, throw new UnsupportedOperationException(s"NodeType '$nodeType' is not a known Swift NodeType!"))(json)
					} else if (tokenKind.nonEmpty) {
						val prefix = { val i = tokenKind.indexOf('('); if (i >= 0) tokenKind.substring(0, i) else tokenKind }
						_tokenKindMap.getOrElse(prefix, throw new UnsupportedOperationException(s"TokenKind '$tokenKind' is not a known Swift TokenKind!"))(json)
					} else {
						throw new UnsupportedOperationException("Invalid SwiftSyntax json element. 'nodeType' and 'tokenKind' cannot be empty at the same time!")
					}
				}

				private val _nodeTypeMap: Map[String, Value => SwiftNode] = Map(
					\(nodeTypeMapEntriesString)
				)

				private val _tokenKindMap: Map[String, Value => SwiftNode] = Map(
					\(tokenKindMapEntriesString)
				)

				sealed trait SwiftNode {
					def json: Value

					protected lazy val _childrenMap: Map[String, Value] = {
						json.obj.get("children") match {
							case Some(ch) => ch.arr.iterator.flatMap(c => c.obj.get("name").map(_.str -> c)).toMap
							case None => Map.empty
						}
					}

					private lazy val _rangeObj = json.obj.get("range").map(_.obj)
					private def _rangeField(name: String): Option[Int] = _rangeObj.flatMap(_.get(name)).map(_.num.toInt)
					def startOffset: Option[Int] = _rangeField("startOffset")
					def endOffset: Option[Int] = _rangeField("endOffset")
					def startLine: Option[Int] = _rangeField("startLine")
					def startColumn: Option[Int] = _rangeField("startColumn")
					def endLine: Option[Int] = _rangeField("endLine")
					def endColumn: Option[Int] = _rangeField("endColumn")

					override lazy val toString: String = this.getClass.getSimpleName.stripSuffix("$")
				}

				sealed trait SwiftToken extends SwiftNode

				// MARK: tokens:
				\(allToken.joined(separator: "\n\t"))

				// MARK: base nodes:
				\(baseNodes.joined(separator: "\n\t"))

				// MARK: marker traits:
				\(allTraits.joined(separator: "\n\t"))

				// MARK: syntax nodes:
				\(allNodes.joined(separator: "\n\t"))

				case class TokenSyntax(json: Value) extends Syntax

			}
			"""

		try out.write(
			to: defaultScalaOutFileUrl,
			atomically: true,
			encoding: String.Encoding.utf8
		)

		print("Generated Scala Swift AST in file: `\(defaultScalaOutFileUrl.path)`")
	}

}
