name: pr

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Install swift 
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "5.9"
      - name: Run Linux Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          swift build
          mv ./.build/debug/SwiftAstGen SwiftAstGen-linux
          ./SwiftAstGen-linux -s
      - name: Run Mac Build
        if: matrix.os == 'macos-latest'
        run: |
          swift build
          mv ./.build/debug/SwiftAstGen SwiftAstGen-mac
          ./SwiftAstGen-mac -s
      - name: Run Windows Build
        if: matrix.os == 'windows-latest'
        run: |
          swift build
          mv .\.build\debug\SwiftAstGen.exe SwiftAstGen-win.exe
          .\SwiftAstGen-win.exe -s
      - name: Run Swift Tests
        run: swift test
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Run Scala Tests
        run: sbt test
        working-directory: ./Tests/ScalaSwiftNodeSyntaxTests
