name: pr

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Install Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          check-latest: true
          development: true
          swift-version: "6.1"
      - name: Run Linux Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          swift sdk install https://download.swift.org/swift-6.1-release/static-sdk/swift-6.1-RELEASE/swift-6.1-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz --checksum 111c6f7d280a651208b8c74c0521dd99365d785c1976a6e23162f55f65379ac6
          swift build --swift-sdk x86_64-swift-linux-musl
          mv ./.build/debug/SwiftAstGen SwiftAstGen-linux
          gzexe SwiftAstGen-linux
          swift build --swift-sdk aarch64-swift-linux-musl
          mv ./.build/debug/SwiftAstGen SwiftAstGen-linux-arm64
          gzexe SwiftAstGen-linux-arm64
          ./SwiftAstGen-linux -s
      - name: Run Mac Build
        if: matrix.os == 'macos-latest'
        run: |
          swift build
          mv ./.build/debug/SwiftAstGen SwiftAstGen-mac
          gzexe SwiftAstGen-mac
          ./SwiftAstGen-mac -s
      - name: Run Windows Build
        if: matrix.os == 'windows-latest'
        run: |
          swift build
          mv .\.build\debug\SwiftAstGen.exe SwiftAstGen-win.exe
          .\SwiftAstGen-win.exe -s
      - name: Run UPX for Windows Build
        if: matrix.os == 'windows-latest'
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            SwiftAstGen-win.exe
          args: -fq
      - name: Run Swift Tests
        run: swift test
      - name: Set up JDK
        if: matrix.os != 'windows-latest'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Run Scala Tests
        run: sbt test
        working-directory: ./Tests/ScalaSwiftNodeSyntaxTests
