name: pr

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Install swift (Linux and MacOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        uses: swift-actions/setup-swift@v1.25.0
        with:
          swift-version: "5.9"
      - name: Install swift (Windows)
        if: matrix.os == 'windows-latest'
        uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.9-release
          tag: 5.9-RELEASE
      - name: Run Tests
        run: swift test
