name: pr

on:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install older glibc
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install libc-bin=2.31-0ubuntu9.17 libc6=2.31-0ubuntu9.17
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Install Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          check-latest: true
          development: true
          swift-version: "5.10"
      - name: Run Linux Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          swift build
          mv ./.build/debug/SwiftAstGen SwiftAstGen-linux
          gzexe SwiftAstGen-linux
          ./SwiftAstGen-linux -s
      - name: Run Mac Build
        if: matrix.os == 'macos-latest'
        run: |
          swift build
          mv ./.build/debug/SwiftAstGen SwiftAstGen-mac
          gzexe SwiftAstGen-mac
          ./SwiftAstGen-mac -s
      - name: Run Windows Build
        if: matrix.os == 'windows-latest'
        run: |
          swift build
          mv .\.build\debug\SwiftAstGen.exe SwiftAstGen-win.exe
          .\SwiftAstGen-win.exe -s
      - name: Run UPX for Windows Build
        if: matrix.os == 'windows-latest'
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            SwiftAstGen-win.exe
          args: -fq
      - name: Run Swift Tests
        run: swift test
      - name: Set up JDK
        if: matrix.os != 'windows-latest'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'
      - name: Run Scala Tests
        run: sbt test
        working-directory: ./Tests/ScalaSwiftNodeSyntaxTests
