name: release

on:
  push:
    tags:
      - '**' 

concurrency: production

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Install Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          check-latest: true
          development: true
          swift-version: "6.1"
          visual-studio-components: Microsoft.VisualStudio.Component.Windows11SDK.22621
      - name: Run Linux Build
        if: matrix.os == 'ubuntu-latest'
        run: |
          swift sdk install https://download.swift.org/swift-6.1-release/static-sdk/swift-6.1-RELEASE/swift-6.1-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz --checksum 111c6f7d280a651208b8c74c0521dd99365d785c1976a6e23162f55f65379ac6
          swift build --swift-sdk x86_64-swift-linux-musl -c release --static-swift-stdlib
          mv ./.build/release/SwiftAstGen SwiftAstGen-linux
          gzexe SwiftAstGen-linux
          swift build --swift-sdk aarch64-swift-linux-musl -c release --static-swift-stdlib
          mv ./.build/release/SwiftAstGen SwiftAstGen-linux-arm64
          gzexe SwiftAstGen-linux-arm64
          ./SwiftAstGen-linux -s
      - name: Run Mac Build
        if: matrix.os == 'macos-latest'
        run: |
          xcrun --toolchain ${{ env.TOOLCHAINS }} swift build -c release --arch arm64 --arch x86_64
          mv ./.build/apple/Products/Release/SwiftAstGen SwiftAstGen-mac
          gzexe SwiftAstGen-mac
      - name: Run Windows Build
        if: matrix.os == 'windows-latest'
        run: |
          swift build -c release --arch x86_64 --static-swift-stdlib
          mv .\.build\release\SwiftAstGen.exe SwiftAstGen-win.exe
      - name: Run UPX for Windows Build
        if: matrix.os == 'windows-latest'
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            SwiftAstGen-win.exe
          args: -fq
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            SwiftAstGen-linux
            SwiftAstGen-linux-arm64
            SwiftAstGen-mac
            SwiftAstGen-win.exe
            SwiftNodeSyntax.scala
